#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  ./release-github.sh [options]

Description:
  Creates or updates a GitHub release for LaneAssist using the newest module zip,
  and uploads signature metadata for future auto-update verification.

Defaults:
  --repo UranVester/LaneAssist
  --zip  latest file matching laneassist-module*.zip in current folder
  --tag  derived from zip filename (laneassist-module-vX.Y.zip -> vX.Y)
  --title "LaneAssist <tag>"

Options:
  --repo OWNER/REPO           GitHub repository (default: UranVester/LaneAssist)
  --zip PATH                  Explicit zip file to release
  --tag TAG                   Explicit release tag (example: v1.2)
  --title TITLE               Explicit release title
  --notes-file FILE           Use existing notes file instead of autogenerated notes
  --secret-key-b64 BASE64     Ed25519 secret key (or use env var LANEASSIST_UPDATE_SECRET_KEY_B64)
  --draft                     Create/edit as draft release
  --prerelease                Create/edit as prerelease
  --latest                    Mark release as latest (default)
  --no-latest                 Do not force latest flag
  -h, --help                  Show this help

Required tools:
  gh, php (libsodium), sha256sum
EOF
}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="UranVester/LaneAssist"
ZIP_PATH=""
TAG=""
TITLE=""
NOTES_FILE=""
SECRET_KEY_B64="${LANEASSIST_UPDATE_SECRET_KEY_B64:-}"
IS_DRAFT=0
IS_PRERELEASE=0
SET_LATEST=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)
      REPO="$2"
      shift 2
      ;;
    --zip)
      ZIP_PATH="$2"
      shift 2
      ;;
    --tag)
      TAG="$2"
      shift 2
      ;;
    --title)
      TITLE="$2"
      shift 2
      ;;
    --notes-file)
      NOTES_FILE="$2"
      shift 2
      ;;
    --secret-key-b64)
      SECRET_KEY_B64="$2"
      shift 2
      ;;
    --draft)
      IS_DRAFT=1
      shift
      ;;
    --prerelease)
      IS_PRERELEASE=1
      shift
      ;;
    --latest)
      SET_LATEST=1
      shift
      ;;
    --no-latest)
      SET_LATEST=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

command -v gh >/dev/null 2>&1 || { echo "gh command not found" >&2; exit 1; }
command -v php >/dev/null 2>&1 || { echo "php command not found" >&2; exit 1; }
command -v sha256sum >/dev/null 2>&1 || { echo "sha256sum command not found" >&2; exit 1; }

php -r 'if (!function_exists("sodium_crypto_sign_detached")) { fwrite(STDERR, "libsodium extension missing in PHP\n"); exit(2); }'

gh auth status >/dev/null 2>&1 || {
  echo "gh is not authenticated. Run: gh auth login" >&2
  exit 1
}

if [[ -z "$ZIP_PATH" ]]; then
  ZIP_PATH="$(ls -1t "$SCRIPT_DIR"/laneassist-module*.zip 2>/dev/null | head -n 1 || true)"
fi

if [[ -z "$ZIP_PATH" || ! -f "$ZIP_PATH" ]]; then
  echo "No release zip found. Build one first with ./build-update.sh" >&2
  exit 1
fi

ZIP_PATH="$(cd "$(dirname "$ZIP_PATH")" && pwd)/$(basename "$ZIP_PATH")"
ZIP_BASENAME="$(basename "$ZIP_PATH")"

if [[ -z "$TAG" ]]; then
  if [[ "$ZIP_BASENAME" =~ ^laneassist-module-v(.+)\.zip$ ]]; then
    TAG="v${BASH_REMATCH[1]}"
  elif [[ "$ZIP_BASENAME" =~ ^laneassist-module-(.+)\.zip$ ]]; then
    TAG="${BASH_REMATCH[1]}"
  else
    TAG="release-$(date +%Y%m%d-%H%M%S)"
  fi
fi

if [[ -z "$TITLE" ]]; then
  TITLE="LaneAssist ${TAG}"
fi

if [[ -z "$SECRET_KEY_B64" ]]; then
  echo "Missing secret key. Use --secret-key-b64 or LANEASSIST_UPDATE_SECRET_KEY_B64" >&2
  exit 1
fi

ZIP_SHA256="$(sha256sum "$ZIP_PATH" | awk '{print $1}')"
ZIP_SIGNATURE="$(LANEASSIST_UPDATE_SECRET_KEY_B64="$SECRET_KEY_B64" php -r '
$hash = trim((string)$argv[1]);
$secretB64 = getenv("LANEASSIST_UPDATE_SECRET_KEY_B64");
if ($hash === "") {
  fwrite(STDERR, "Empty hash input\n");
  exit(3);
}
$secret = sodium_base642bin($secretB64, SODIUM_BASE64_VARIANT_ORIGINAL);
$signature = sodium_crypto_sign_detached($hash, $secret);
echo sodium_bin2base64($signature, SODIUM_BASE64_VARIANT_ORIGINAL), PHP_EOL;
' "$ZIP_SHA256")"

TMP_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

SHA_FILE="$TMP_DIR/${ZIP_BASENAME}.sha256"
SIG_FILE="$TMP_DIR/${ZIP_BASENAME}.sig"
printf "%s  %s\n" "$ZIP_SHA256" "$ZIP_BASENAME" > "$SHA_FILE"
printf "%s\n" "$ZIP_SIGNATURE" > "$SIG_FILE"

if [[ -z "$NOTES_FILE" ]]; then
  NOTES_FILE="$TMP_DIR/release-notes.md"
  cat > "$NOTES_FILE" <<EOF
Release asset: ${ZIP_BASENAME}

Installation:
1. Go to your IANSEO root folder.
2. Extract this zip in place.
3. Confirm final module path is Modules/Custom/LaneAssist.

Signature metadata for updater verification:
- SHA-256: ${ZIP_SHA256}
- Signature (Ed25519 over SHA-256 hex):

\`\`\`
${ZIP_SIGNATURE}
\`\`\`
EOF
fi

CREATE_FLAGS=()
if [[ "$IS_DRAFT" -eq 1 ]]; then
  CREATE_FLAGS+=(--draft)
fi
if [[ "$IS_PRERELEASE" -eq 1 ]]; then
  CREATE_FLAGS+=(--prerelease)
fi
if [[ "$SET_LATEST" -eq 1 ]]; then
  CREATE_FLAGS+=(--latest)
fi

if gh release view "$TAG" --repo "$REPO" >/dev/null 2>&1; then
  echo "Release ${TAG} already exists in ${REPO}. Updating assets and notes..."
  gh release upload "$TAG" "$ZIP_PATH" "$SHA_FILE" "$SIG_FILE" --repo "$REPO" --clobber
  gh release edit "$TAG" --repo "$REPO" --title "$TITLE" --notes-file "$NOTES_FILE"
else
  echo "Creating release ${TAG} in ${REPO}..."
  gh release create "$TAG" "$ZIP_PATH" "$SHA_FILE" "$SIG_FILE" --repo "$REPO" --title "$TITLE" --notes-file "$NOTES_FILE" "${CREATE_FLAGS[@]}"
fi

echo ""
echo "Release complete"
echo "Repo:      $REPO"
echo "Tag:       $TAG"
echo "Asset:     $ZIP_BASENAME"
echo "SHA-256:   $ZIP_SHA256"
echo "Signature: $ZIP_SIGNATURE"
